# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
#default: &default
 # adapter: sqlite3
  #pool: 5
  #timeout: 5000



development:
 adapter: postgresql
 database: flybit_development
 pool: 5
 timeout: 5000
 host: localhost

production:
 adapter: postgresql
 database: flybit_production
 pool: 5
 timeout: 5000
 host: localhost

test:
 adapter: postgresql
 database: flybit_test
 pool: 5
 timeout: 5000
 host: localhost
